name: Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linux-test-build-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: ["5.2", "latest"]
    container:
      image: swift:${{ matrix.swift }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Test
        run: |
          - swift test --generate-linuxmain
          - make test
      - name: Build Release
        run: make buildRelease
